apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html-site
  template:
    metadata:
      labels:
        app: simple-html-site
    spec:
      containers:
        - name: simple-html-site
          image: ammar55/html:latest  # Apni Docker image ka naam yahan dalain
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
spec:
  selector:
    app: simple-html-site
  ports:
    - protocol: TCP
      port: 80          # Service ka internal port
      targetPort: 80    # Container ka port
      nodePort: 30080   # Custom NodePort (30000-32767 range mein hona chahiye)
  type: NodePort
